name: Build and Deploy

on:
  push:
    branches:
      - prod

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18.17.1

    - name: Install dependencies
      run: |
        npm install

    - name: Build frontend
      run: |
        npm run build

    - name: Start backend
      run: |
        npm run api_start

